<template>
  <loading-view :loading="loading">
    <heading class="mb-6">{{ __("Two factor auth") }}</heading>
    <loading-card :loading="loading" class="card">
      <div class="p-3" v-if="status.confirmed == 1">
        <p class="mb-4">
          {{ __("Update your two factor security settings") }}
        </p>
        <input
          v-model="status.enabled"
          type="radio"
          name="status"
          :value="1"
          id="s1"
        />
        <label for="s1">{{ __("Enabled") }}</label>
        <input
          v-model="status.enabled"
          type="radio"
          name="status"
          :value="0"
          id="s2"
        />
        <label for="s2">{{ __("Disabled") }}</label>
        <br />
        <button @click="toggle" class="mt-2 btn btn-default btn-primary">
          {{ __("Update") }}
        </button>
      </div>

      <div v-else class="p-3">
        <h3 class="p-3">
          {{ __("What is Two-Factor Authentication?") }}
        </h3>

        <p class="p-2">
          {{
            __(
              "Two factor authentication (2FA) strengthens access security by requiring two methods (also referred to as factors) to verify your identity. Two factor authentication protects against phishing, social engineering and password brute force attacks and secures your logins from attackers exploiting weak or stolen credentials."
            )
          }}
        </p>

        <p class="p-2">
          {{
            __(
              "After enabling this feature, you will need your password, along with the code generated by a dedicated application."
            )
          }}
        </p>

        <p class="p-2">
          {{
            __(
              "Instead of just entering a password to log in, you'll also need to enter a passcode or use a security key. This extra step helps ensure that you, and only you, can access your account."
            )
          }}
        </p>

        <h3 class="px-2 mt-3">{{ __("Recovery code") }}</h3>

        <p class="p-2">
          {{
            __(
              "In case you no longer have access to your device, you can use this code to verify your identity."
            )
          }}
        </p>

        <p class="p-2 no-print">
          <strong>
            {{
              __(
                "Write it down or take a screenshot and keep it somewhere safe. This code can only be used once."
              )
            }}
          </strong>
        </p>

        <div class="p-3 my-2 text-center text-red-900 rec-box">
          <h2 class="mb-2">{{ twofa.recovery }}</h2>
          <a
            @click.prevent="downloadAsText('recover_code.txt', twofa.recovery)"
            href="#"
            >{{ __("Download") }}</a
          >
        </div>

        <h3 class="px-2 mt-3">{{ __("Google Authenticator") }}</h3>

        <p class="p-2">
          {{
            __(
              "To use two-factor authentication, you need to have the Google Authenticator app installed on your phone."
            )
          }}
        </p>

        <div class="flex items-center my-4 text-center">
          <a
            href="https://apps.apple.com/lv/app/google-authenticator/id388497605"
            target="_blank"
            class="w-1/2 mx-2"
          >
            {{ __("Apple version") }}
          </a>

          <a
            href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=it&gl=IT"
            target="_blank"
            class="w-1/2 mx-2"
          >
            {{ __("Android version") }}
          </a>
        </div>

        <h3 class="px-2 mt-3">
          {{ __("Turn on two-factor authentication") }}
        </h3>

        <div class="p-3">
          <p>
            {{
              __(
                "Scan this QR code using the Google Authenticator app and enter the generated OTP code"
              )
            }}
          </p>
          <div class="mt-3 text-center">
            <img width="150" :src="twofa.google2fa_url" alt="qr_code" />
          </div>
          <br />
          <input
            v-model="form.otp"
            @keyup="autoSubmit()"
            placeholder="OTP"
            type="text"
            class="w-full mb-2 form-control form-input form-input-bordered"
          />
          <button @click="confirmOtp" class="btn btn-default btn-primary">
            {{ __("Activate") }}
          </button>
        </div>
      </div>
    </loading-card>
  </loading-view>
</template>

<script>
export default {
  data() {
    return {
      twofa: [],
      form: {},
      status: { registered: false, enabled: 0, confirmed: 0 },
      loading: true,
    };
  },

  mounted() {
    this.getStatus();
    this.getRecoveryCodes();
  },

  methods: {
    getStatus() {
      Nova.request()
        .get("/nova-vendor/nova-two-factor/status")
        .then((res) => {
          this.status = res.data;
          this.loading = false;
        });
    },

    getHome() {
      window.location.href = "/admin";
    },

    getRecoveryCodes() {
      Nova.request()
        .get("/nova-vendor/nova-two-factor/register")
        .then((res) => {
          this.twofa = res.data;
        });
    },

    toggle() {
      Nova.request()
        .post("/nova-vendor/nova-two-factor/toggle", {
          status: this.status.enabled,
        })
        .then((res) => {
          this.$toasted.show(res.data.message, { type: "success" });
        });
    },

    confirmOtp() {
      Nova.request()
        .post("/nova-vendor/nova-two-factor/confirm", this.form)
        .then((res) => {
          this.$toasted.show(res.data.message, { type: "success" });

          this.getHome();
        })
        .catch((err) => {
          this.$toasted.show(err.response.data.message, {
            type: "error",
          });
        });
    },

    autoSubmit() {
      if (this.form.otp.length === 6) {
        this.confirmOtp();
      }
    },
    downloadAsText(filename, text) {
      var element = document.createElement("a");
      element.setAttribute(
        "href",
        "data:text/plain;charset=utf-8," + encodeURIComponent(text)
      );
      element.setAttribute("download", filename);

      element.style.display = "none";
      document.body.appendChild(element);

      element.click();

      document.body.removeChild(element);
    },
  },
};
</script>
